import 'package:flutter/material.dart';

import 'palette.dart';

class AppColorSchemes {
  const AppColorSchemes._();

  static const ColorScheme light = ColorScheme(
    brightness: Brightness.light,
    primary: AppPalette.blue600,
    onPrimary: Colors.white,
    primaryContainer: Color(0xFFE3F2FD),
    onPrimaryContainer: AppPalette.navy900,
    secondary: AppPalette.teal500,
    onSecondary: AppPalette.navy900,
    secondaryContainer: Color(0xFFD7F2F4),
    onSecondaryContainer: AppPalette.navy900,
    tertiary: AppPalette.lime400,
    onTertiary: AppPalette.navy900,
    tertiaryContainer: Color(0xFFF2F8DC),
    onTertiaryContainer: AppPalette.navy900,
    error: AppPalette.red400,
    onError: Colors.white,
    errorContainer: Color(0xFFFAD5D0),
    onErrorContainer: Color(0xFF410001),
    background: AppPalette.gray50,
    onBackground: AppPalette.navy900,
    surface: Colors.white,
    onSurface: AppPalette.navy900,
    surfaceVariant: AppPalette.gray100,
    onSurfaceVariant: AppPalette.gray600,
    outline: AppPalette.gray300,
    outlineVariant: AppPalette.gray100,
    shadow: Colors.black26,
    scrim: Colors.black54,
    inverseSurface: AppPalette.navy900,
    onInverseSurface: Colors.white,
    inversePrimary: AppPalette.blue700,
    surfaceTint: AppPalette.blue600,
  );

  static const ColorScheme dark = ColorScheme(
    brightness: Brightness.dark,
    primary: AppPalette.blue600,
    onPrimary: Colors.white,
    primaryContainer: Color(0xFF0F1F36),
    onPrimaryContainer: Colors.white,
    secondary: AppPalette.teal500,
    onSecondary: Colors.black,
    secondaryContainer: Color(0xFF0F3F44),
    onSecondaryContainer: Colors.white,
    tertiary: AppPalette.lime400,
    onTertiary: Colors.black,
    tertiaryContainer: Color(0xFF374014),
    onTertiaryContainer: Colors.white,
    error: AppPalette.red400,
    onError: Colors.black,
    errorContainer: Color(0xFF5B1A12),
    onErrorContainer: Colors.white,
    background: AppPalette.gray900,
    onBackground: Colors.white,
    surface: AppPalette.gray800,
    onSurface: Colors.white,
    surfaceVariant: AppPalette.gray700,
    onSurfaceVariant: AppPalette.gray300,
    outline: Color(0xFF334155),
    outlineVariant: AppPalette.gray700,
    shadow: Colors.black,
    scrim: Colors.black54,
    inverseSurface: Colors.white,
    onInverseSurface: AppPalette.gray900,
    inversePrimary: AppPalette.blue600,
    surfaceTint: AppPalette.blue600,
  );
}
